Code refactoring
IvanGlinkin/CCTV pull request #36
Opened 2024-05-11 14:55 UTC by paracosm17

Just refactoring the code. The changes almost did not change the behavior of the program

The purpose of the fixes is to standardize the code to pep8, fix codestyle and identations, improve the performance and readability of the code

1. Fix comments, empty strings, imports. Add ".idea" to .gitignore
2. Fix "if" expressions. Fix lantitude, longitude types in "coordinates_overage" (from int to float). Remove timestamp from coordinates_overage (line 132 in original start.py), because redefined without timestamp in line 202, and so, timestamp in coordinates_overage is not used.
Added better exception handling when opening a generated html file in the browser
3. Code refactoring in functions.py. Added better get_location_details. The function "pring_city_by_geo" has been renamed to "print_city_by_geo". remove lon_rad from calculate_coordinates because not used. Change R to r. Correction of minor defects.

2024-05-11 16:15 UTC, ask0n commented
Hi @paracosm17 to keep code standard across future changes we need to have pipeline with a linter, could you please add it as a part of this PR?
[Ruff](https://github.com/astral-sh/ruff) would be a preferred one.

2024-05-11 18:34 UTC, paracosm17 commented
> Hi @paracosm17 to keep code standard across future changes we need to have pipeline with a linter, could you please add it as a part of this PR? [Ruff](https://github.com/astral-sh/ruff) would be a preferred one.

Hello, I'll add It today

2024-05-14 07:06 UTC, ask0n commented
/run_ci

2024-05-14 07:43 UTC, paracosm17 commented
/run_ci

2024-05-14 07:55 UTC, ask0n commented
/run_ci

2024-05-14 08:07 UTC, ask0n commented
/run_ci

2024-05-14 08:12 UTC, ask0n commented
/run_ci

2024-05-14 08:21 UTC, ask0n commented
/run_ci

2024-05-14 19:35 UTC, ask0n commented
/run_ci

2024-05-14 19:40 UTC, ask0n commented
/run_ci

2024-05-14 20:08 UTC, ask0n requested changes

2024-05-14 20:08 UTC, ask0n commented on requirements-dev.txt
> +beautifulsoup4==4.12.3
Without traces in readme this file will be confusing. Do we need it?

2024-05-14 20:08 UTC, ask0n commented on backend/functions.py
> +            },
Since we do not check line length it is better to keep unified code style for this map.
I.e. each parameter on new line or keep existent definition.

2024-05-14 20:08 UTC, ask0n commented on backend/functions.py
> +            },
same as above

2024-05-14 20:08 UTC, ask0n commented on start.py
> +                            ),  # Check if the peer_located is of type PeerLocated
can we keep this on a single line to clearly see all three checks one per line?

2024-05-16 13:37 UTC, merged